use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub address: String,
    pub port: u16,
    pub width: u32,
    pub height: u32,
    pub mode: String,
    pub enable_auth: bool,
    pub username: String,
    pub password: String,
    pub tls_enabled: bool,
    pub tls_cert_path: String,
    pub tls_key_path: String,
    pub rsa_key_path: String,
    pub autostart: bool,
    pub minimize_to_tray: bool,
    pub binary_path: String,
    #[serde(default)]
    pub onboarding_complete: bool,

    /* Performance / GPU settings (written to config.ini for the backend) */
    #[serde(default = "default_gpu_mode")]
    pub gpu_mode: String,
    #[serde(default = "default_drm_device")]
    pub drm_device: String,
    #[serde(default = "default_fps_default")]
    pub fps_default: u32,
    #[serde(default = "default_fps_max")]
    pub fps_max: u32,
    #[serde(default = "default_pw_buffers")]
    pub pw_buffers: u32,
    #[serde(default = "default_pw_buffers_min")]
    pub pw_buffers_min: u32,
    #[serde(default = "default_pw_buffers_max")]
    pub pw_buffers_max: u32,
}

fn default_gpu_mode()      -> String { "auto".into() }
fn default_drm_device()    -> String { "auto".into() }
fn default_fps_default()   -> u32   { 144 }
fn default_fps_max()       -> u32   { 240 }
fn default_pw_buffers()    -> u32   { 2 }
fn default_pw_buffers_min() -> u32  { 2 }
fn default_pw_buffers_max() -> u32  { 4 }

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            address: "0.0.0.0".into(),
            port: 5900,
            width: 1920,
            height: 1080,
            mode: "virtual".into(),
            enable_auth: false,
            username: String::new(),
            password: String::new(),
            tls_enabled: false,
            tls_cert_path: String::new(),
            tls_key_path: String::new(),
            rsa_key_path: String::new(),
            autostart: false,
            minimize_to_tray: true,
            binary_path: String::new(),
            onboarding_complete: false,
            gpu_mode: default_gpu_mode(),
            drm_device: default_drm_device(),
            fps_default: default_fps_default(),
            fps_max: default_fps_max(),
            pw_buffers: default_pw_buffers(),
            pw_buffers_min: default_pw_buffers_min(),
            pw_buffers_max: default_pw_buffers_max(),
        }
    }
}

/// Write ~/.config/touchvnc-gnome/config.ini so the backend picks up
/// GPU and performance settings (which have no CLI arg equivalents).
fn write_backend_ini(config: &AppConfig, dir: &std::path::PathBuf) -> Result<(), String> {
    let content = format!(
        "# Generated by touchvnc-gnome-gui — do not edit manually\n\
         [server]\n\
         address = {address}\n\
         port = {port}\n\
         width = {width}\n\
         height = {height}\n\
         mode = {mode}\n\
         \n\
         [capture]\n\
         fps_default = {fps_default}\n\
         fps_max = {fps_max}\n\
         pw_buffers = {pw_buffers}\n\
         pw_buffers_min = {pw_buffers_min}\n\
         pw_buffers_max = {pw_buffers_max}\n\
         \n\
         [gpu]\n\
         mode = {gpu_mode}\n\
         drm_device = {drm_device}\n",
        address     = config.address,
        port        = config.port,
        width       = config.width,
        height      = config.height,
        mode        = config.mode,
        fps_default = config.fps_default,
        fps_max     = config.fps_max,
        pw_buffers      = config.pw_buffers,
        pw_buffers_min  = config.pw_buffers_min,
        pw_buffers_max  = config.pw_buffers_max,
        gpu_mode    = config.gpu_mode,
        drm_device  = config.drm_device,
    );

    std::fs::write(dir.join("config.ini"), content)
        .map_err(|e| format!("Failed to write config.ini: {}", e))
}

fn config_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
    PathBuf::from(home)
        .join(".config")
        .join("touchvnc-gnome")
}

fn config_path() -> PathBuf {
    config_dir().join("config.toml")
}

#[tauri::command]
pub fn load_config() -> AppConfig {
    let path = config_path();
    match std::fs::read_to_string(&path) {
        Ok(content) => toml::from_str(&content).unwrap_or_default(),
        Err(_) => AppConfig::default(),
    }
}

#[tauri::command]
pub fn save_config(config: AppConfig) -> Result<(), String> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create config directory: {}", e))?;

    // Write GUI state (TOML)
    let content =
        toml::to_string_pretty(&config).map_err(|e| format!("Failed to serialize config: {}", e))?;
    std::fs::write(config_path(), content)
        .map_err(|e| format!("Failed to write config file: {}", e))?;

    // Write backend performance/GPU config (INI — no CLI arg equivalents)
    write_backend_ini(&config, &dir)?;

    Ok(())
}

#[tauri::command]
pub fn get_default_config() -> AppConfig {
    AppConfig::default()
}

/// Returns true if onboarding wizard should be shown.
/// Shows wizard if: config file doesn't exist OR onboarding_complete is false.
#[tauri::command]
pub fn needs_onboarding() -> bool {
    let path = config_path();
    match std::fs::read_to_string(&path) {
        Ok(content) => {
            let config: AppConfig = toml::from_str(&content).unwrap_or_default();
            !config.onboarding_complete
        }
        Err(_) => true, // No config file = first run
    }
}

#[tauri::command]
pub fn complete_onboarding() -> Result<(), String> {
    let mut config = load_config();
    config.onboarding_complete = true;
    save_config(config)
}
